import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/general/MainWrapper";
import { Toaster } from 'react-hot-toast';
import emailjs from '@emailjs/browser';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize EmailJS
emailjs.init(process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY!);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center`}
      >
        <Wrapper>{children}</Wrapper>
        <Toaster
          position="top-right"
          toastOptions={{
            className: '',
            style: {
              background: '#14141e',
              color: '#ffffff',
              padding: '16px',
              borderRadius: '8px',
              fontSize: '14px',
              maxWidth: '400px',
              fontFamily: 'var(--font-geist-sans)',
              border: '1px solid #4f8fff',
              boxShadow: '0 0 15px rgba(79, 143, 255, 0.3)',
            },
            success: {
              duration: 5000,
              style: {
                border: '1px solid #4f8fff',
                boxShadow: '0 0 15px rgba(79, 143, 255, 0.3)',
              },
            },
            error: {
              duration: 5000,
              style: {
                border: '1px solid #4f8fff',
                boxShadow: '0 0 15px rgba(79, 143, 255, 0.3)',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
