// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  navbar: dynamic(() => import("./Navbar")),
  projects: dynamic(() => import("./Projects")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
};
